name: canopy-flow
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - gdal
  - geopandas
  - rasterio
  - xgboost
  - scikit-learn
  - optuna
  - matplotlib
  - pandas
  - rasterio
  - pdal
  - pip
  - pip:
      - earthengine-api==1.7.17
      - spatial-kfold
      - boto3
      - metaflow
      - laspy
      - omegaconf
      - hydra-core
      - dotenv
      - geemap
      - duckdb==1.4.4 
      - pyarrow
      - geedim